clc; clear; close all;

%% Plant model
s = tf('s');
G = 1 / ((s+2)*(8*s+1));   % G(s) = 1/((s+2)(8s+1))

%% Simulation parameters
Ts = 0.01; Tfinal = 50; t = (0:Ts:Tfinal)';
r = ones(size(t));                       % unit step reference
% Disturbance: step at t=20 s
d = [zeros(1, round(20/Ts)), 0.2*ones(1, length(t)-round(20/Ts))]';
% Measurement noise (small random)
rng(0);
n = 0.001 * randn(size(t));

%% ---- Multi‑objective optimization function (accepts external data) ----
function [J1, J2] = multiObjectiveFunction(x, G, t, r, d, n)
    Kp = x(1); Ki = x(2); Kd = x(3); b = x(4); tau = x(5);
    if tau <= 0
        J1 = 1e6; J2 = 1e6; return;
    end
    metrics = evaluateController(Kp, Ki, Kd, b, tau, G, t, r, d, n);
    J1 = metrics.ISE + 10*metrics.rise_time + 100*metrics.overshoot;
    J2 = metrics.IAE_dist + 0.1*metrics.var_u;
end

%% ---- Helper function to evaluate controller performance ----
function metrics = evaluateController(Kp, Ki, Kd, b, tau, G, t, r, d, n)
    s = tf('s');
    % Modified PID controller: derivative on output + set‑point weighting
    C_r = Kp*b + Ki/s;                     % feedforward from reference
    C_y = Kp + Ki/s + Kd*s/(tau*s+1);      % feedback from output

    % Closed‑loop transfer functions
    T_yr = feedback(G*C_r, C_y);           % y/r
    T_yd = feedback(G, C_y);               % y/d  (disturbance at plant input)
    T_yn = feedback(1, G*C_y);             % y/n  = 1/(1+G*C_y)
    T_un = -feedback(C_y, G*C_y);          % u/n  (negative)

    % Reference tracking (no disturbance, no noise)
    [y_ref, ~] = step(T_yr, t);
    e_ref = r - y_ref;
    metrics.ISE = sum(e_ref.^2) * (t(2)-t(1));

    % Rise time (10% → 90%)
    idx10 = find(y_ref >= 0.1, 1);
    idx90 = find(y_ref >= 0.9, 1);
    if isempty(idx10) || isempty(idx90)
        metrics.rise_time = t(end);
    else
        metrics.rise_time = t(idx90) - t(idx10);
    end

    % Overshoot
    yss = dcgain(T_yr);
    if isnan(yss), yss = 1; end
    metrics.overshoot = max(0, max(y_ref) - yss)/yss;

    % Disturbance rejection
    y_dist = lsim(T_yd, d, t);
    metrics.IAE_dist = sum(abs(y_dist)) * (t(2)-t(1));

    % Noise sensitivity (variance of control signal)
    [~, u_noise] = lsim(T_un, n, t);
    metrics.var_u = var(u_noise);
end

%% ---- Run Pareto optimization ----
lb = [0, 0, 0, 0, 0.01];   % [Kp, Ki, Kd, b, tau]
ub = [10, 10, 10, 1, 0.5];

% Capture external variables in an anonymous function
objFcn = @(x) multiObjectiveFunction(x, G, t, r, d, n);

options = optimoptions('paretosearch', ...
    'ParetoSetSize', 50, ...
    'Display', 'iter', ...
    'PlotFcn', @psplotparetof);   % Corrected plot function

fprintf('Running Pareto search...\n');
[x_pareto, f_pareto] = paretosearch(objFcn, 5, [], [], [], [], lb, ub, [], options);

% Select knee point as compromise solution
f_norm = f_pareto ./ max(f_pareto, [], 1);
distances = sqrt(sum(f_norm.^2, 2));
[~, knee_idx] = min(distances);
knee_solution = x_pareto(knee_idx, :);
fprintf('Knee solution: Kp=%.4f, Ki=%.4f, Kd=%.4f, b=%.4f, tau=%.4f\n', ...
    knee_solution(1), knee_solution(2), knee_solution(3), knee_solution(4), knee_solution(5));

save('pareto_results.mat', 'x_pareto', 'f_pareto', 'knee_solution');
% The Pareto front plot is automatically generated by paretosearch; save it
saveas(gcf, 'pareto_front.png');

%% ---- Parametric studies ----
% Use knee solution as baseline
Kp0 = knee_solution(1); Ki0 = knee_solution(2); Kd0 = knee_solution(3);
b0 = knee_solution(4); tau0 = knee_solution(5);

% Effect of set‑point weighting b
b_vals = 0:0.1:1;
ISE_b = zeros(size(b_vals)); IAE_b = zeros(size(b_vals));
for i = 1:length(b_vals)
    met = evaluateController(Kp0, Ki0, Kd0, b_vals(i), tau0, G, t, r, d, n);
    ISE_b(i) = met.ISE; IAE_b(i) = met.IAE_dist;
end
figure;
plot(b_vals, ISE_b, 'b-o', b_vals, IAE_b, 'r-s'); grid on;
xlabel('Set-point weighting b'); ylabel('Performance');
legend('ISE (Tracking)', 'IAE (Disturbance)');
title('Effect of b on Performance');
saveas(gcf, 'b_sweep.png');

% Effect of derivative filter time constant tau
tau_vals = 0.01:0.01:0.5;
var_u_tau = zeros(size(tau_vals)); ISE_tau = zeros(size(tau_vals));
for i = 1:length(tau_vals)
    met = evaluateController(Kp0, Ki0, Kd0, b0, tau_vals(i), G, t, r, d, n);
    var_u_tau(i) = met.var_u; ISE_tau(i) = met.ISE;
end
figure;
yyaxis left; plot(tau_vals, var_u_tau, 'b-'); ylabel('Control signal variance');
yyaxis right; plot(tau_vals, ISE_tau, 'r-'); ylabel('ISE');
xlabel('Derivative filter time constant \tau'); grid on;
legend('Var(u)', 'ISE');
title('Effect of \tau on noise sensitivity');
saveas(gcf, 'tau_sweep.png');

% Robustness to parameter variations (±15% in denominator coefficients)
nom_den = [8, 17, 2];
pert_vals = [0.85, 1, 1.15];
ISE_robust = zeros(size(pert_vals)); IAE_robust = zeros(size(pert_vals));
for i = 1:length(pert_vals)
    scale = pert_vals(i);
    den_pert = [nom_den(1), nom_den(2)*scale, nom_den(3)*scale];
    G_pert = tf(1, den_pert);
    met = evaluateController(Kp0, Ki0, Kd0, b0, tau0, G_pert, t, r, d, n);
    ISE_robust(i) = met.ISE; IAE_robust(i) = met.IAE_dist;
end
figure;
plot(pert_vals, ISE_robust, 'b-o', pert_vals, IAE_robust, 'r-s');
xlabel('Scaling factor'); ylabel('Performance');
legend('ISE', 'IAE dist');
title('Robustness to parameter variations');
grid on;
saveas(gcf, 'robustness.png');

%% Final step response of the optimal controller
C_r_opt = tf([Kp0*b0 Ki0], [1 0]);
C_y_opt = tf([Kd0+Kp0*tau0, Kp0+Ki0*tau0, Ki0], [tau0, 1, 0]);
T_yr_opt = feedback(G*C_r_opt, C_y_opt);
T_yd_opt = feedback(G, C_y_opt);

figure;
step(T_yr_opt, t); grid on;
title('Step response with optimal modified PID');
saveas(gcf, 'optimal_step.png');

figure;
step(T_yd_opt, t); grid on;
title('Disturbance response');
saveas(gcf, 'disturbance_response.png');

disp('All simulations completed. Figures saved.');